# -*- coding: utf-8 -*-
"""Advanced Oral Bioavailability Screening | Comparative Analysis of Lipinski, Ghose, and Veber Rules Using Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SimvMOA1LURYwm1YAq0xsObTYKtKeesH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# 'properties.csv' is in the root of your Google Drive , (change the path below to where YOU saved tha dataset file)
file_path = '/content/drive/MyDrive/properties.csv'
df = pd.read_csv(file_path)

print('Successfully loaded properties.csv into a DataFrame.')
display(df.head())

# CELL 1: Initial Inspection
# Quick sanity check: how many rows/columns and what are we working with?

print("Shape of the dataset (rows, columns):", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

df.head()

# CELL 2: Data Cleaning & Renaming
# "Molecule" column holds SMILES strings, not names — rename for clarity.

df = df.rename(columns={'Molecule': 'SMILES'})

df.head()

# CELL 3: Column Extraction
# Extract only the descriptor columns needed for screening rules.
# .copy() ensures clean_df is truly independent.

clean_df = df[['Molecular Formula', 'XLogP', 'Molecular Weight',
               'Hydrogen Bond Donors', 'Hydrogen Bond Acceptors',
               'SMILES', 'Element Count' ,'Topological Polar Surface Area',
               'Rotatable Bonds Count']].copy()

print("Shape of the updated dataset (rows, columns):", clean_df.shape)
print("\nColumn names:")
print(clean_df.columns.tolist())

clean_df.head(10)

columns = clean_df.columns.tolist()
#  Cell 4: Move 'SMILES' column to be after 'Molecular Formula' for logical grouping
columns.remove('SMILES')
columns.insert(columns.index('Molecular Formula') + 1, 'SMILES')

clean_df = clean_df[columns]

clean_df.head()

# CELL 5: Handling Missing Values (With Conditional Logic)
# Check for NaN values and drop rows if needed.

missing_counts = clean_df.isnull().sum()
print("Missing values per column:")
print(missing_counts)

total_missing = missing_counts.sum()

if total_missing > 0:
    rows_before = clean_df.shape[0]
    clean_df.dropna(inplace=True)
    rows_after = clean_df.shape[0]
    rows_dropped = rows_before - rows_after
    print(f"\nDropped {rows_dropped} rows containing missing values.")
    print(f"Rows remaining: {rows_after}")
else:
    print("\nNo missing values found. Dataset is clean.")

# CELL 6 :Convert numeric columns to proper numeric type.
# CSV imports sometimes store numbers as text — pd.to_numeric() fixes this and coerces errors to NaN.
# This ensures all comparisons in later cells work correctly (e.g., HBD > 5).

clean_df['Hydrogen Bond Donors'] = pd.to_numeric(clean_df['Hydrogen Bond Donors'], errors='coerce')
clean_df['Hydrogen Bond Acceptors'] = pd.to_numeric(clean_df['Hydrogen Bond Acceptors'], errors='coerce')
clean_df['Molecular Weight'] = pd.to_numeric(clean_df['Molecular Weight'], errors='coerce')
clean_df['XLogP'] = pd.to_numeric(clean_df['XLogP'], errors='coerce')
clean_df['Element Count'] = pd.to_numeric(clean_df['Element Count'], errors='coerce')
clean_df['Topological Polar Surface Area'] = pd.to_numeric(clean_df['Topological Polar Surface Area'], errors='coerce')
clean_df['Rotatable Bonds Count'] = pd.to_numeric(clean_df['Rotatable Bonds Count'], errors='coerce')

print("\nNumeric conversion complete. All descriptor columns are ready for calculations.")

# CELL 7: Calculating Violations (The Scientific Logic)
# --- Lipinski's Rule of Five ---
# Classic baseline for oral drug-likeness: HBD/HBA/MW/LogP constraints.
# Counting violations keeps granularity for analysis.

# calculate 'Lipinski_Violations' after ensuring numeric types
clean_df['Lipinski_Violations'] = (
    (clean_df['Hydrogen Bond Donors'] > 5).astype(int) +
    (clean_df['Hydrogen Bond Acceptors'] > 10).astype(int) +
    (clean_df['Molecular Weight'] >= 500).astype(int) +
    (clean_df['XLogP'] > 5).astype(int)
      )

clean_df.sample(10)

# CELL 8 : --- Ghose Filter ---
# Lipinski only flags high LogP, missing hydrophilic extremes.
# Ghose adds strict lower AND upper bounds on LogP (-0.4 to 5.6), MW, and atom count.
# Molar Refractivity omitted: it's redundant with MW + Element Count (both measure bulkiness).

clean_df['Ghose_Violations'] = (
    (~clean_df['XLogP'].between(-0.4, 5.6)).astype(int) +
    (~clean_df['Molecular Weight'].between(160, 480)).astype(int) +
    (~clean_df['Element Count'].between(20, 70)).astype(int)
      )

clean_df.sample(10)

# CELL 9 : --- Veber's Rules ---
# Lipinski/Ghose focus on LogP and size. Veber adds structural angle:
# flexibility (rotatable bonds) and polarity (TPSA) also affect absorption.

clean_df['Veber_Violations'] = (
    (clean_df['Rotatable Bonds Count'] > 10).astype(int) +
    (clean_df['Topological Polar Surface Area'] > 140).astype(int)
     )

clean_df.sample(10)

# CELL 10: Applying Pass/Fail, The Sweet Spot & Consensus Column
# Convert violation counts to ✅/❌ labels for easy scanning and filtering.

clean_df['Lipinski_Pass'] = clean_df['Lipinski_Violations'].apply(
    lambda x : '✅ Pass' if x <= 1 else '❌ Fail'
    )

# Ghose stays strict (zero tolerance) since the rule is already simplified.
clean_df['Ghose_Pass'] = clean_df['Ghose_Violations'].apply(
    lambda x : '✅ Pass' if x == 0 else '❌ Fail'
    )

clean_df['Veber_Pass'] = clean_df['Veber_Violations'].apply(
    lambda x : '✅ Pass' if x == 0 else '❌ Fail'
    )

# Sweet Spot is optimal LogP range, not just acceptable
clean_df['Sweet_Spot_Pass'] = clean_df['XLogP'].apply(
     lambda x: '✅ Pass' if 0.5 < x < 3.5 else '❌ Fail'
    )

# Consensus: pass only if ALL four filters clear simultaneously.
clean_df['All_Rules_Pass'] = clean_df.apply(
      lambda row: '✅ Pass' if (
             row['Lipinski_Pass'] == '✅ Pass' and
             row['Ghose_Pass'] == '✅ Pass' and
             row['Veber_Pass'] == '✅ Pass' and
             row['Sweet_Spot_Pass'] == '✅ Pass'
             )    else '❌ Fail',
      axis=1
            )

clean_df.sample(10)

# CELL 11: Comparative Summary & Value Counts with Percentages
# How many compounds pass/fail each rule? Shows the effect of tightening criteria.

print("LIPINSKI RULE")
print(" "*60)
lipinski_counts = clean_df['Lipinski_Pass'].value_counts()
print(lipinski_counts)
print("\nPercentages:")
print((lipinski_counts / len(clean_df) * 100).round(2))

print("\n" + "="*60)
print("GHOSE FILTER")
print(" "*60)
ghose_counts = clean_df['Ghose_Pass'].value_counts()
print(ghose_counts)
print("\nPercentages:")
print((ghose_counts / len(clean_df) * 100).round(2))

print("\n" + "="*60)
print("VEBER RULES")
print(" "*60)
veber_counts = clean_df['Veber_Pass'].value_counts()
print(veber_counts)
print("\nPercentages:")
print((veber_counts / len(clean_df) * 100).round(2))

print("\n" + "="*60)
print("SWEET SPOT")
print(" "*60)
sweet_spot_counts = clean_df['Sweet_Spot_Pass'].value_counts()
print(sweet_spot_counts)
print("\nPercentages:")
print((sweet_spot_counts / len(clean_df) * 100).round(2))

print("\n" + "="*60)
print("CONSENSUS (All Rules)")
print(" "*60)
all_rules_counts = clean_df['All_Rules_Pass'].value_counts()
print(all_rules_counts)
print("\nPercentages:")
print((all_rules_counts / len(clean_df) * 100).round(2))

print("\n" + "="*60)
print("Final Results Sample (10 random compounds):")
print(" "*60)
clean_df[['Molecular Formula', 'SMILES',
          'Lipinski_Violations', 'Ghose_Violations', 'Veber_Violations',
          'Lipinski_Pass', 'Ghose_Pass', 'Veber_Pass',
          'Sweet_Spot_Pass', 'All_Rules_Pass']].sample(10)

# Cell 12 : displaying results using barcharts :
import matplotlib.pyplot as plt

# Dictionary for text properties (title, xlabel, ylabel)
text_properties = {
    'fontsize': 18,
    'fontweight': 'bold'
            }

# Create figure with 4 subplots (2x2 grid)
fig, axes = plt.subplots(2, 2, figsize=(14, 12))
fig.suptitle('Drug-Likeness Rule Pass/Fail Percentages', fontsize=24, fontweight='bold', color='black')


# Lipinski Pass - Blue
axes[0, 0].bar(lipinski_percentages.index.astype(str), lipinski_percentages.values, color='blue')
axes[0, 0].set_title('Lipinski Rule of 5', **text_properties , color='blue')
axes[0, 0].set_xlabel('Results', **text_properties  )
axes[0, 0].set_ylabel('Percentage of Compounds', **text_properties )

# Ghose Pass - Red
axes[0, 1].bar(ghose_percentages.index.astype(str), ghose_percentages.values, color='red')
axes[0, 1].set_title('Ghose Filter', **text_properties , color= 'blue')
axes[0, 1].set_xlabel('Results', **text_properties )
axes[0, 1].set_ylabel('Percentage of Compounds', **text_properties)

# Veber Pass - Green
axes[1, 0].bar(veber_percentages.index.astype(str), veber_percentages.values, color='green')
axes[1, 0].set_title('Veber\'s rule', **text_properties , color = 'blue')
axes[1, 0].set_xlabel('Results', **text_properties)
axes[1, 0].set_ylabel('Percentage of Compounds', **text_properties)

# All Rules Pass - Purple
axes[1, 1].bar(all_rules_percentages.index.astype(str), all_rules_percentages.values, color='purple')
axes[1, 1].set_title('Consensus (All Rules)', **text_properties ,color= 'blue')
axes[1, 1].set_xlabel('Results', **text_properties)
axes[1, 1].set_ylabel('Percentage of Compounds', **text_properties)

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap

plt.savefig('Bioavailability_Screening_Charts.png', dpi=300, bbox_inches='tight')
plt.show()

# CELL 13: Exporting Final Report to Google Drive
# Save results to CSV .

clean_df.to_csv('/content/drive/My Drive/Advanced_Drug_Screening_Results.csv', index=False)

print("✅ Exported: Advanced_Drug_Screening_Results.csv")
print("📂 Location : Google Drive > My Drive")